# Generated by Django 3.1.2 on 2021-02-22 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Credentials', max_length=200)),
                ('client_secret_filename', models.CharField(default='client_secret_1.json', max_length=200)),
                ('redirect_uri', models.CharField(default='', max_length=200)),
                ('scopes', models.TextField(default='["https://www.googleapis.com/auth/spreadsheets.readonly","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/drive.file"]')),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Credentials', max_length=200)),
                ('token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_uri', models.TextField(blank=True)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
