# Generated by Django 3.1.2 on 2021-02-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleoauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauth',
            name='scopes',
            field=models.TextField(default='["https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/drive.file"]'),
        ),
    ]
