# Generated by Django 3.1.2 on 2021-03-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleoauth', '0002_auto_20210225_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthusers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
