# Generated by Django 3.1.2 on 2021-03-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleoauth', '0003_oauthusers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauth',
            name='scopes',
            field=models.TextField(default='["https://www.googleapis.com/auth/spreadsheets.readonly","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/drive.file"]'),
        ),
    ]
