# Generated by Django 3.1.2 on 2021-02-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('token_id', models.TextField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('token_start_time', models.DateTimeField(auto_now_add=True)),
                ('token_expiry_time', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='dependencies',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
