# Generated by Django 3.1.2 on 2021-02-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrator'), (2, 'creator'), (3, 'departmental_creator'), (4, 'viewer'), (5, 'others')], default=1),
        ),
    ]
