# Generated by Django 3.1.2 on 2021-03-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Company', max_length=200)),
                ('folder_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
