# Generated by Django 3.1.2 on 2021-03-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210309_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='milestone_sheet_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='task_sheet_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
